listen: ":8088"
upstreams:
  users:
    # url: "http://userservice:8081"
    # local test
    url: "http://localhost:8081"
  orders:
    # url: "http://orderservice:8082"
    # local test
    url: "http://localhost:8082"
routes:
  - path: "/users"
    upstream: users
  - path: "/orders"
    upstream: orders